### ISSUE TITLE
stack exec futr says "does not exist"

### ISSUE THREAD

**Issue by andersaamodt** [AutonomousOrganization/futr2#1]
Here is the full output. It seems like it's trying to connect to an onion address? Maybe for bootstrapping?

`Just ("cvpcawhvxk27qvu5xrcblx7ingfxfivukesdpj7rwg63mflaly3tbuid.onion",80,"/")
futr: Network.Socket.getAddrInfo (called with preferred socket type/protocol: AddrInfo {addrFlags = [], addrFamily = AF_UNSPEC, addrSocketType = Stream, addrProtocol = 0, addrAddress = 0.0.0.0:0, addrCanonName = Nothing}, host name: Just "cvpcawhvxk27qvu5xrcblx7ingfxfivukesdpj7rwg63mflaly3tbuid.onion", service name: Just "80"): does not exist (Name or service not known)`

Are you running tor as root to get it to work?

**Comment by AutonomousOrganization** [comment]
That is the error you get when attempting to resolve an onion without using a proxy. Master branch has more relays in the bootstrap (so you will get more errors... and also hopefully some live events too)

**Comment by AutonomousOrganization** [comment]
Close this because that meant it worked
