### ISSUE TITLE
Front-end bootstrap issues

### ISSUE THREAD

**Issue by ZenenTreadwell** [AutonomousOrganization/futr2#11]
Getting everything up and running, I ran into a build issue where freetype2 was missing from my system. On debian, I installed libfreetype-dev and was able to complete the build. 

When running, I'm getting an error:
`futr: Network.Socket.connect: <socket: 25>: does not exist (Connection refused)`

Which socket is it looking for?

**Comment by ZenenTreadwell** [comment]
Also, can we have a `stack-exec futr-relay`? I can't run my project on the current commit because the GUI keeps the relay from booting :(

**Comment by AutonomousOrganization** [comment]
Apologies, shouldn't have gone to master with the monomer stuff ;p. 

`stack exec relay` exists now

**Comment by ZenenTreadwell** [comment]
`futr: SDLCallFailed {sdlExceptionCaller = "SDL.Video.glCreateContext", sdlFunction = "SDL_GL_CreateContext", sdlExceptionError = "Could not create GL context: GLXBadFBConfig"}`                                    

oops - closed this before the actual GUI issue was addressed - I'm also seeing this above error, not sure if that helps

**Comment by AutonomousOrganization** [comment]
To confirm, did you do? : 
- [SDL2 and GLEW](https://github.com/fjvallarino/monomer/blob/main/docs/tutorials/00-setup.md#libraries-sdl2-and-glew)

**Comment by ZenenTreadwell** [comment]
yep, both packages are installed and up-to-date

**Comment by ZenenTreadwell** [comment]
I've been messing around with it a bit, it seems like an issue with how my OS handles graphics. I'm going to try getting it going on a clean system and see if that helps.

**Comment by ZenenTreadwell** [comment]
Update - rebuilt this on a properly working computer (Debian 12.2 base, kernel 6.1) and was able to successfully boot the GUI. closing this issue unless it pops up again.
