### ISSUE TITLE
Relay fails to boot

### ISSUE THREAD

**Issue by ZenenTreadwell** [AutonomousOrganization/futr2#15]
https://github.com/AutonomousOrganization/futr2/commit/59ecee4501b36abb33219f4c67f299ab3c3f0341#commitcomment-134753403

See the above message. I needed to revert to the previous commit to keep my relay running.

**Comment by AutonomousOrganization** [comment]
Odd. There are a couple suspect things in that commit: 

- a change to relay/Main (the linter was saying redundant brackets) 
- language spec in package (I'll put it back to GHC2021)

**Comment by AutonomousOrganization** [comment]
Oh, could it be it's silently failing to migrate db?

**Comment by AutonomousOrganization** [comment]
Before closing: Prevent MonadFail inside createDb from silently stopping
