### ISSUE TITLE
querying for only Kind 0 does not seem to work

### ISSUE THREAD

**Issue by ZenenTreadwell** [AutonomousOrganization/futr2#2]
Leveraging tooling from [nostr-tools](https://www.npmjs.com/package/nostr-tools?activeTab=readme#interacting-with-a-relay), I am able to successfully make a query for all Events of kind 1, as well as all posts of kinds 1 and 0. However, a query of only kind 0 returns nothing. 

I am using the built-in relay.list function as demonstrated near the bottom of the linked code segment.

**Comment by AutonomousOrganization** [comment]
Thanks for this issue, I had gone half way on a bad design choice and never went back. Unfortunately it looks like the change is not migrating the db so need to `mv` or `rm` the old one. I want beam migrate to let me never make backwards incompatible db changes but I can't figure out setting the default of a non nullable field at the moment and don't want to have a Maybe for a field that will always be there
