### ISSUE TITLE
Inconsistent broadcasting via WebSocket

### ISSUE THREAD

**Issue by ZenenTreadwell** [AutonomousOrganization/futr2#3]
I'm having some issues when it comes to receiving updates over WebSocket. When I publish an event, I always receive an OK in response. ~90% of the time, though, I don't get the post published back to me over websocket. This behaviour is independent for each client connection with no apparent pattern to when the first/second/both/neither clients will have the event broadcast to them. I need the relay to publish the event back to me 100% of the time for consistent front-end updates.

If you have any ideas about why this would be happening (could it be related to the undefined behaviour that you were mentioning in the test cases?), I can try to tackle this myself. I just need to know where to look.

Here's a bit of packet data, maybe it will help?
**sent packets that are acked and also received back)**
```
["EVENT",
{"kind":1,
pubkey":"13ac861e79a2f6bd7f591ec1a00ae495ee71712a4b2ea951ab722227912add57",
"created_at":1695855777,
"tags":[
["e","492ee3e4aed08e1aeec7e5087e741b2310e99a25aad7ccec62576170a6e08c9e","ws://localhost:9481/","root"],
["p","13ac861e79a2f6bd7f591ec1a00ae495ee71712a4b2ea951ab722227912add57"]
],
"content":"something??",
"id":"50f37ae5898343e3db4a62bf903d9f490ad8c7b437832b4147e111eba2844b9f",
"sig":"91937bac01eb9279ce2ea561e9e319425bd2c4e250a84be71e4a5c039c700823c684c08b9511444c2a1edcf77c3d2c65e1937a6deab6c83753daa288dae59a5d"
}]
```
```
["EVENT",{"kind":1,"pubkey":"13ac861e79a2f6bd7f591ec1a00ae495ee71712a4b2ea951ab722227912add57","created_at":1695857546,"tags":[["e","492ee3e4aed08e1aeec7e5087e741b2310e99a25aad7ccec62576170a6e08c9e","ws://localhost:9481/","root"],["p","13ac861e79a2f6bd7f591ec1a00ae495ee71712a4b2ea951ab722227912add57"]],"content":"dang bro","id":"2b109366289ba0b0d387a719c2fafaa3399661df4ade583717c839af65d9d6ea","sig":"0258600044f2b0f7fe9c8c254e44a90b8fdd311c20f4e653679bdfd74c5e19347b1c95b2eefe4724b46c0a74e0f14b069105828311f6bc3af5ae43366cf9e8ed"}]
```
```
["EVENT",{"kind":1,"pubkey":"13ac861e79a2f6bd7f591ec1a00ae495ee71712a4b2ea951ab722227912add57","created_at":1695857546,"tags":[["e","492ee3e4aed08e1aeec7e5087e741b2310e99a25aad7ccec62576170a6e08c9e","ws://localhost:9481/","root"],["p","13ac861e79a2f6bd7f591ec1a00ae495ee71712a4b2ea951ab722227912add57"]],"content":"dang bro","id":"2b109366289ba0b0d387a719c2fafaa3399661df4ade583717c839af65d9d6ea","sig":"0258600044f2b0f7fe9c8c254e44a90b8fdd311c20f4e653679bdfd74c5e19347b1c95b2eefe4724b46c0a74e0f14b069105828311f6bc3af5ae43366cf9e8ed"}]
```

**sent (acked, not received back)**
```
["EVENT",{"kind":1,
"pubkey":"13ac861e79a2f6bd7f591ec1a00ae495ee71712a4b2ea951ab722227912add57",
"created_at":1695856302,
"tags":[
["e","492ee3e4aed08e1aeec7e5087e741b2310e99a25aad7ccec62576170a6e08c9e","ws://localhost:9481/","root"],
["p","13ac861e79a2f6bd7f591ec1a00ae495ee71712a4b2ea951ab722227912add57"]
],
"content":"this one don't work tho", 
"id":"4f745126cd476c8500ed92075dfd8712f19b3b6a08e237b8f405275894036665",
"sig":"2e4ca6ad6b325c69828d12833fb6c78cd5e376b790b5fe770d4a70798294e96497ae2da9a4dee95e02bc19da872a85acd0c5c3ed7b1467db982f71937760e09c"
}]
```
```
["EVENT",{"kind":1,"pubkey":"13ac861e79a2f6bd7f591ec1a00ae495ee71712a4b2ea951ab722227912add57","created_at":1695857546,"tags":[["e","492ee3e4aed08e1aeec7e5087e741b2310e99a25aad7ccec62576170a6e08c9e","ws://localhost:9481/","root"],["p","13ac861e79a2f6bd7f591ec1a00ae495ee71712a4b2ea951ab722227912add57"]],"content":"dang bro","id":"2b109366289ba0b0d387a719c2fafaa3399661df4ade583717c839af65d9d6ea","sig":"0258600044f2b0f7fe9c8c254e44a90b8fdd311c20f4e653679bdfd74c5e19347b1c95b2eefe4724b46c0a74e0f14b069105828311f6bc3af5ae43366cf9e8ed"}]
```

**Comment by AutonomousOrganization** [comment]
I'm going to try and get a test to replicate this. See no reason

**Comment by ZenenTreadwell** [comment]
I don't think so. I can post identical data with differing results. I feel like it has something to do with the ECDA signatures and them not passing tests consistently. I'm trying to figure out how it works but there's a lot of code to get up-to-speed on.

**Comment by AutonomousOrganization** [comment]
It's the schnorr signatures that are in use (the difference between schnorr and ecdsa is small but confusing, need to figure it out to get the diffie-hellman (ecdh) to work, which is the first part of nip4, but none of that is relevant here). 

If the signature failed you would get back ["OK", False, "signature failed"] 
https://github.com/AutonomousOrganization/futr2/blob/9b1af61759588d442eb7e0a9b83c82c5707ae374/src/Nostr/Relay.hs#L93C18-L93C18

**Comment by AutonomousOrganization** [comment]
Would it mess it up if the event came back before the OK (seems that is the case).

**Comment by ZenenTreadwell** [comment]
Are you able to replicate what's going on? It doesn't seem to be an issue that the event is returned before the OK.

**Comment by AutonomousOrganization** [comment]
Yeah I am seeing events go in the db without hitting the sqlite changefeed / TChan Event which is how the broadcast works so didn't think that would be possible

**Comment by AutonomousOrganization** [comment]
It seems when another process registers the changefeed function it steals it from the previous process holder . . . // really the harvester was just a test and I think the relay should be it's own executable which may just fix it.

**Comment by AutonomousOrganization** [comment]
Ok, I think I fixed it. I wasn't properly duplicating the TChan so it wasn't a new process that was stealing it but a new client connection. I'll let you close this if it does fix

**Comment by ZenenTreadwell** [comment]
I think that this has made my day. Comments are properly updating live across multiple browsers with consistency - huge boost to the UI for my app. Thanks for resolving this!
