### ISSUE TITLE
NIP-02: index out of bounds (0,0)

### ISSUE THREAD

**Issue by ZenenTreadwell** [AutonomousOrganization/futr2#5]
I know that NIP-02 isn't officially supported, but it doesn't seem like it would be a problem based on the format.
```
index out of bounds (0,0) 
CallStack (from HasCallStack):
  error, called at src/Data/Vector/Internal/Check.hs:100:12 in vector-0.13.0.0-7XqAjxGD9I5JHFrMQ5lSZ8:Data.Vector.Internal.Check
  checkError, called at src/Data/Vector/Internal/Check.hs:106:17 in vector-0.13.0.0-7XqAjxGD9I5JHFrMQ5lSZ8:Data.Vector.Internal.Check
  check, called at src/Data/Vector/Internal/Check.hs:119:5 in vector-0.13.0.0-7XqAjxGD9I5JHFrMQ5lSZ8:Data.Vector.Internal.Check
  checkIndex, called at src/Data/Vector/Generic.hs:245:11 in vector-0.13.0.0-7XqAjxGD9I5JHFrMQ5lSZ8:Data.Vector.Generic
  !, called at src/Data/Vector.hs:495:7 in vector-0.13.0.0-7XqAjxGD9I5JHFrMQ5lSZ8:Data.Vector
```

I get the above error when I try to publish the following event: 

```
{
  "kind": 3,
  "pubkey": "fa0977e756b78f900895975a0333dc7bc0ecde1878236964a5e0c9de6c843b10",
  "created_at": 1698180569,
  "tags": [
    [
      "p",
      "0c56849c21ba030f52d84f66606f5582a7bf0be532ab10c7b6026e3c0305e505",
      "wss://solar.credenso.cafe",
      "bsg"
    ]
  ],
  "content": "",
  "id": "ce4e2f5dea894700aa605c19a00919ac60ab3f54008f9e018f6a2b9a205c2fbc",
  "sig": "dee3ccfbaf2a37f4fbbc1b36005bc5e1c370c8043f76e67571b39fc3e906a41929d9f765ca23f044a19e4891b644c59a056e44ff7cff86bcdcf0e3603313b52c"
}
```
It seems to sign without an issue so I'm not quite sure what would be happening on the relay side - any ideas?

**Comment by ZenenTreadwell** [comment]
I'm not sure actually... it might be something on my end. Seems like there might be a failed signature somewhere in here. Will try to update soon.

**Comment by AutonomousOrganization** [comment]
My code assumes the length of the "p" tag is 2 or 3, relay optional. So what is probably happening is the "bsg" in that tag is getting thrown out, then the signature is failing after. 

So think I can fix it by supporting that additional field in the p tag (looking at nip 2 now probably should do)

**Comment by AutonomousOrganization** [comment]
Ugly error that is confusing / don't understand why (0,0) / out of bounds

**Comment by ZenenTreadwell** [comment]
Problem solved. I had accidentally pushed an empty list to the list of tags, which is probably where the (0,0) comes from. Thanks for the update!
