### ISSUE TITLE
limit query ordering

### ISSUE THREAD

**Issue by ZenenTreadwell** [AutonomousOrganization/futr2#6]
According to NIP-01,

> When limit: n is present it is assumed that the events returned in the initial query will be the last n events ordered by the created_at. It is safe to return less events than limit specifies, but it is expected that relays do not return (much) more events than requested so clients don't get unnecessarily overwhelmed by data.

Does futr2 limit the events returned in forward or backward ordering?

**Comment by AutonomousOrganization** [comment]
Good catch. The fetch doesn't do any sorting so it probably is by id or by created ascending. Sort is expensive so I kinda hate to add it to fetch but that is what I will do and optimizations later.
