### ISSUE TITLE
Futr crashing on Direct Message

### ISSUE THREAD

**Issue by ZenenTreadwell** [AutonomousOrganization/futr2#8]
```
{
  "kind": 4,
  "pubkey": "fa0977e756b78f900895975a0333dc7bc0ecde1878236964a5e0c9de6c843b10",
  "created_at": 1698429452,
  "tags": [
    [
      "p",
      "0c56849c21ba030f52d84f66606f5582a7bf0be532ab10c7b6026e3c0305e505"
    ]
  ],
  "content": "Ae/eIHGb1n8RLdgD9rKLqvZ8Tqf1aDVLXlAg5T9/fi87lbKuC7it",
  "id": "862ffd7baa160a2d30d05ff991dc19b42ed3c2cd8576adfadab5544233df73aa",
  "sig": "19d91228750f5f70736fb54368f972d88282ea01a58eff9b0365bfe110be9c905d94e220795a3cca9864229d0049aed4743399488a7d8ea2f4319ad044942ad1"
}
```

The above event causes the relay to crash with the following message:
```
"e : Ae/eIHGb1n8RLdgD9rKLqvZ8Tqf1aDVLXlAg5T9/fi87lbKuC7it"
"p : \"fa0977e756b78f900895975a0333dc7bc0ecde1878236964a5e0c9de6c843b10\""
futr: invalid content
CallStack (from HasCallStack):
  error, called at src/Nostr/Direct.hs:99:10 in futr2-0.1.0.0-96iAYENGyElIIDxI1bdedN:Nostr.Direct
```

The event was created using the 'nostr-tools' package, pretty much exactly following the guide exactly:
https://www.npmjs.com/package/nostr-tools?activeTab=readme#encrypting-and-decrypting-direct-messages

**Comment by ZenenTreadwell** [comment]
Oh... I'm missing the initialization vector... lol going to leave this open till I fix it though

**Comment by AutonomousOrganization** [comment]
Any bad content that causes a crash is def a bug I should fix. I've left a bunch of error "xxx" around and really need to either handle them there or handle errors globally. (Nip 44?)

**Comment by ZenenTreadwell** [comment]
Oh, also - DMs aren't permitted without auth, right? I don't think that's listed in the README (or the process of how to authorize, though I'm sure that's standardized somewhere)

**Comment by AutonomousOrganization** [comment]
Should happen automatically. Challenge is sent out on every connection and if the client supports it should do it.

**Comment by ZenenTreadwell** [comment]
Okay, I'm building my own client but I'll go look around about how it works.

**Comment by AutonomousOrganization** [comment]
https://github.com/AutonomousOrganization/futr2/blob/0c22bc9d016de30f062c2a6cc0ba78d92dcf5995/src/Nostr/Auth.hs#L18

Above authenticate function creates the authentication event. The Text field is the text that is sent down in the Challenge tag.

**Comment by ZenenTreadwell** [comment]
Okay, authentication is working and I can publish DMs now... but it's still crashing with 
```
"e : 1Jtv709UTQJ/LAlxFn282Q==?iv=V7n8LWG0PXRYJsb1kr5CjQ=="
"p : \"0c56849c21ba030f52d84f66606f5582a7bf0be532ab10c7b6026e3c0305e505\""
futr: Cannot decode byte '\x9d': Data.Text.Encoding: Invalid UTF-8 stream
```
Not sure if I'm missing a step with publishing the message or what

**Comment by AutonomousOrganization** [comment]
Ok, this may be fine and you did it correctly (this error is being caught and not crashing right? I think it's in the decryptE in app/Main which is in a try). Is the direct message you are sending to the key on the relay that prints on the start? If not then this error would be expected because it is trying to decrypt all kind 4 without checking if it is actually meant for our key.

**Comment by ZenenTreadwell** [comment]
Yea, this is a message that's being sent from the key denoted by P in the log. I think you're on the right track here.

**Comment by ZenenTreadwell** [comment]
What's the rationale for making futr responsible for the decryption of the DMs? I was assuming that I'd have to handle it client-side.

**Comment by AutonomousOrganization** [comment]
Just testing, all the logging / relay connecting stuff. Sent from that key? or to it?

**Comment by AutonomousOrganization** [comment]
Think that eventually should split the Nostr Library from the relay implementation. Your right the relay will never need to decrypt a msg, it's a client thing

**Comment by ZenenTreadwell** [comment]
The message was sent from the user with the 0c5 pubkey.

**Comment by AutonomousOrganization** [comment]
Think you may have it backwards. The keypair that prints on startup is generated or retrieved from the identities table

**Comment by ZenenTreadwell** [comment]
```
$ stack exec futr
"me pub"
"\"7f8bacc9f5282d31d32de98f721dd3d53cb9253779cfa58a4df80b51cdd7ad62\""
"me priv"
"\"42db817...[removed]\""
"sent auth (rec challenge)"
ConnectionClosed
futr: ConnectionClosed
"e : nBab16RecQl83alhL2oZlA==?iv=H8rQjfWEjHFD4E8OD8kVFw=="
"p : \"fa0977e756b78f900895975a0333dc7bc0ecde1878236964a5e0c9de6c843b10\""
futr: Cannot decode byte '\x8f': Data.Text.Encoding: Invalid UTF-8 stream
```
This is the trace from my logging on as user fa0977 and sending a message to user 0c5. Neither one corresponds to the key that's printed on startup.

**Comment by AutonomousOrganization** [comment]
Ok a bad decrypt using an incorrect key is expected. I added Maybe contexts and key check on the decrypt so should be gone now

**Comment by ZenenTreadwell** [comment]
Awesome! It's no longer crashing, seems like things are good
